// Ticket titles generated by the audit-to-ticket flow always follow this
// exact shape (see AuditFillForm's handleSubmit in Audit.jsx):
//   "Audit NO - {section title}: {item label} ({brand})"
const AUDIT_TICKET_TITLE = /^Audit NO - (.+?): (.+) \((.+)\)$/;

function ticketGroupKey(ticket) {
  const match = AUDIT_TICKET_TITLE.exec(ticket.title || '');
  if (!ticket.audit_template_id || !match) return null;
  const [, section, item] = match;
  return [
    ticket.audit_template_id,
    section.trim().toLowerCase(),
    item.trim().toLowerCase(),
    (ticket.store_name || '').trim().toLowerCase(),
  ].join('::');
}

// Collapses repeat NO-answer tickets (same checklist template, same failed
// item, same store) into a single visible "head" ticket per open issue.
// Any ticket that comes in while the current head is still unresolved is
// folded into that head's duplicate log instead of appearing as its own
// row. Once the head is closed, the next ticket in the group becomes the
// new head and starts a fresh duplicate count.
//
// This is purely a display transform — every ticket still exists as its
// own row in the database exactly as it does today. Nothing is written
// back; this just decides what's shown vs. collapsed.
//
// Dynamic by construction: grouping is keyed by audit_template_id, so any
// future template with active_ticket enabled gets its own grouping and its
// own row in the resulting duplicate breakdown automatically.
export function groupDuplicateTickets(tickets, templatesById = {}) {
  const groups = new Map();
  const result = [];

  for (const ticket of tickets) {
    const key = ticketGroupKey(ticket);
    if (!key) {
      result.push(ticket);
      continue;
    }
    if (!groups.has(key)) groups.set(key, []);
    groups.get(key).push(ticket);
  }

  for (const groupTickets of groups.values()) {
    const sorted = [...groupTickets].sort(
      (a, b) => (Date.parse(a.created_date) || 0) - (Date.parse(b.created_date) || 0)
    );

    let head = sorted[0];
    let dupEntries = [];

    const flush = () => {
      const templateTitle = templatesById[head.audit_template_id]?.title || 'Resubmissions';
      result.push(
        dupEntries.length > 0
          ? {
              ...head,
              _duplicates: { [templateTitle]: dupEntries },
              _duplicateTicketIds: dupEntries.map(e => e.id),
            }
          : head
      );
    };

    for (let i = 1; i < sorted.length; i++) {
      const ticket = sorted[i];
      if (head.status === 'closed') {
        flush();
        head = ticket;
        dupEntries = [];
      } else {
        dupEntries.push({ id: ticket.id, created_date: ticket.created_date });
      }
    }
    flush();
  }

  return result;
}